#!/bin/sh
now=$(date +%F_%T)
echo "$now - daily updated updated" >> /tmp/deezerupdates
#wget --post-data 'url=https://www.deezer.com/en/playlist/5158987484&quality=flac' http://192.168.0.104:1732/api/download/?
